/**
 * Generates public/favicon.svg: the kanji 落 ("fall") from Yuji Syuku, the
 * identity's display face, as an SVG path on the ground colour (second-pass
 * spec §5.3). Deterministic; re-run only if the face or the tokens change.
 * Run: npm run build:favicon
 */
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import opentype from 'opentype.js';

const GLYPH = '落';
const SIZE = 64;
const FONT_DIR = 'node_modules/@fontsource/yuji-syuku/files';
const OUT = 'public/favicon.svg';

function token(name: string): string {
  const css = readFileSync('src/ui/tokens.css', 'utf8');
  const match = new RegExp(`${name}:\\s*(#[0-9a-fA-F]{6})\\s*;`).exec(css);
  if (match === null) throw new Error(`tokens.css has no ${name}`);
  return match[1].toLowerCase();
}

/** opentype.js 2.x dropped loadSync (it is a logging stub); parse the bytes. */
function loadFont(path: string): opentype.Font {
  return opentype.parse(new Uint8Array(readFileSync(path)).buffer);
}

/** Fontsource splits Japanese into unicode-range slices; find the one that
 *  carries the glyph. opentype.js reads WOFF (not WOFF2). */
function fontWith(glyph: string): opentype.Font {
  for (const file of readdirSync(FONT_DIR).filter((f) => f.endsWith('-400-normal.woff')).sort()) {
    const font = loadFont(join(FONT_DIR, file));
    if (font.charToGlyphIndex(glyph) !== 0) return font;
  }
  throw new Error(`no Yuji Syuku slice contains ${glyph}`);
}

const font = fontWith(GLYPH);
const fontSize = SIZE * 0.84;
const glyph = font.charToGlyph(GLYPH);
const advance = (glyph.advanceWidth ?? font.unitsPerEm) * (fontSize / font.unitsPerEm);
const x = (SIZE - advance) / 2;
const y = SIZE * 0.5 + fontSize * 0.36; // optical centre for a square CJK glyph
const d = font.getPath(GLYPH, x, y, fontSize).toPathData(2);

const svg =
  `<svg xmlns="http://www.w3.org/2000/svg" width="${SIZE}" height="${SIZE}" viewBox="0 0 ${SIZE} ${SIZE}">\n` +
  `<!-- ${GLYPH} (fall) in Yuji Syuku, generated by scripts/build-favicon.ts; colours from src/ui/tokens.css -->\n` +
  `<rect width="${SIZE}" height="${SIZE}" fill="${token('--color-ground')}"/>\n` +
  `<path d="${d}" fill="${token('--color-ink')}" stroke="${token('--color-system')}" stroke-width="1.2" stroke-linejoin="round"/>\n` +
  `</svg>\n`;
writeFileSync(OUT, svg);
console.log(`wrote ${OUT} (${svg.length} bytes)`);
